spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dbusers
#    url: jdbc:mysql://127.0.0.1:3306/dbusers?useUnicode=true&amp;characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/dbsuperwifi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update #create update validate
      show-sql: true


